kind: pipeline
name: default

volumes:
  - name: docker
    host:
      path: /var/cache/drone/${DRONE_REPO}/${DRONE_STAGE_NAME}

steps:
- name: setup
  image: alpine
  environment: &setup_env
    APP_VER_MAJOR: 1
    APP_VER_MINOR: 0
    APP_VER_PATCH: 13
  commands:
    - echo "$${APP_VER_MAJOR}.$${APP_VER_MINOR}.$${APP_VER_PATCH}-$${DRONE_BUILD_NUMBER}" > VERSION
    - echo -e -n "$${APP_VER_MAJOR}" > .tags
    - echo -e -n ",$${APP_VER_MAJOR}.$${APP_VER_MINOR}" >> .tags
    - echo -e -n ",$${APP_VER_MAJOR}.$${APP_VER_MINOR}.$${APP_VER_PATCH}" >> .tags
    - echo -e -n ",$${APP_VER_MAJOR}.$${APP_VER_MINOR}.$${APP_VER_PATCH}-$${DRONE_BUILD_NUMBER}" >> .tags
    - echo -e -n ",latest" >> .tags 

- name: publish
  image: plugins/docker
  environment:
    <<: *setup_env
  settings:
    repo: izdock/server-manager
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
  - name: docker
    path: /var/lib/docker
  when:
    event: [push, tag]
    branch: master
